### PR TITLE
test: add comprehensive timeout coverage for all search execution paths

### LINKED ISSUE #686: [TEST] Add test using FT.DEBUG to trigger inf loop in all search paths
** Item not tested **

Add test using ft.debug to trigger inf loop inside a background search code path which is part of evaluating a particular key (1) in the entries fetcher, (2) in the prefilter evaluators and (3) in the predicate evaluators. 
For the background thread operations, test if reader thread remains at `100% cpu or if it is all good and it gracefully times out the cmd within the appropriate duration.

** Testing Method **

Add integration tests

### LINKED ISSUE #769: [BUG] FT.AGGREGATE timeout handling is inferior.
**Describe the bug**

FT.AGGREGATE should check for OOM and timeout before each stage.

**To Reproduce**
Steps to reproduce the behavior. Ideally, a script to reproduce the problem.

**Expected behavior**

**Environment**

Additional information to reproduce the failure

- Valkey Search Module Version
- Valkey Core Version 

**Additional context**

### PR DESCRIPTION
**Pull request by Arunsarma07**
## Summary
This PR adds comprehensive timeout handling and test coverage for both `FT.SEARCH` and `FT.AGGREGATE` commands.

### FT.SEARCH Testing (#686)

Added pausepoint-based integration tests to verify timeout behavior across all search execution paths.

**Added 9 pausepoints in search loops:**
- Entries fetcher loop
- Prefilter evaluation loop
- Inline vector filter
- Text predicates (term, prefix, suffix, fuzzy)
- Composed predicate children iteration

**Added 9 integration tests that:**
- Set a pausepoint to simulate an infinite loop
- Run FT.SEARCH with a 5-second timeout in a background thread
- Verify the server stays responsive (not spinning at 100% CPU)
- Verify the command times out and returns an error

**Coverage includes all query types:**
- Non-vector queries (Tag, Numeric, Text)
- Text searches (term, prefix, suffix, fuzzy, composed)
- Hybrid vector queries (prefiltering and inline filtering)

### FT.AGGREGATE Timeout Fix (#769)

FT.AGGREGATE did not have timeout checks during aggregation stage execution. Added timeout checks before processing stages in both standalone and cluster modes.

---

Closes #686  
Fixes #769

### CODE REVIEW

File: src/commands/ft_aggregate.cc [hunk 1]
```diff
@@ -307,7 +307,10 @@ absl::Status ExecuteAggregationStages(AggregateParameters &parameters,
                                       RecordSet &records) {
   agg_input_records.Increment(records.size());
   for (auto &stage : parameters.stages_) {
-    // Todo Check for timeout
+    // Check for timeout
+    if (parameters.cancellation_token->IsCancelled()) {
+      return absl::CancelledError("Search operation cancelled due to timeout");
```
Comment (KarthikSubbarao) [inline src/commands/ft_aggregate.cc]: Search or Aggregate? What do we normally use for Aggregate command errors?

File: src/query/predicate.cc [hunk 2]
```diff
@@ -127,6 +128,9 @@ EvaluationResult TermPredicate::Evaluate(
     }
     // Search for stem variants - these should all exist from ingestion
     for (const auto &variant : stem_variants) {
+      if (!vmsdk::IsMainThread()) {
```
Comment (KarthikSubbarao) [inline src/query/predicate.cc]: This means we are not testing the timeout of the predicate evaluator which runs on the main thread, right?

File: src/commands/ft_aggregate.cc [hunk 3]
```diff
@@ -390,6 +393,12 @@ bool AggregateParameters::RequiresCompleteResults() const {
 
 void AggregateParameters::SendReply(ValkeyModuleCtx *ctx,
                                     query::SearchResult &result) {
+  if (cancellation_token->IsCancelled()) {
```
Comment (KarthikSubbarao) [inline src/commands/ft_aggregate.cc]: What happens there when partial results are enabled? I was reading the FT Search command for comparison. From the code, it sounds like it just returns the results fetched (Which might not be the complete result set).
For Aggregate, this is probably fine

File: src/commands/ft_aggregate.cc (hunk 1 above)
Comment (Arunsarma07) [reply src/commands/ft_aggregate.cc]: I'll make a correction. It should be Aggregate here as the check is in the execution stage of FT.AGGREGATE.

File: src/query/predicate.cc (hunk 2 above)
Comment (Arunsarma07) [reply src/query/predicate.cc]: Correct. I have added the tests for background thread executions for various search paths. But as far as the main thread execution there is a generic test `test_timeoutCMD` in the same `test_cancel.py` file which forces a timeout. I can add some more tests if needed.

File: src/commands/ft_aggregate.cc (hunk 3 above)
Comment (Arunsarma07) [reply src/commands/ft_aggregate.cc]: I think there was a brief discussion on this that we do not return any kind of partial results for the timeout for FT.AGGREGATE command.

Comment (allenss-amazon) [reply src/commands/ft_aggregate.cc]: Correct, for aggregate, there really isn't interesting "partial results". So a timeout for this command should always be reported as a timeout.

File: integration/test_cancel.py [hunk 4]
```diff
@@ -9,6 +9,8 @@
 import logging
 from typing import Any, Union
 from valkeytestframework.util import waiters
+import threading
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py:12]: This test is 700 lines long. Is there anything here which can be cleaned up before I review it? Try checking for existing helper methods and not creating one off functions for this test

File: src/indexes/text.cc [hunk 5]
```diff
@@ -185,6 +186,9 @@ std::unique_ptr<indexes::text::TextIterator> TermPredicate::BuildTextIterator(
     }
     // Search for stem variants - these should all exist from ingestion
     for (const auto &variant : stem_variants) {
+      if (!vmsdk::IsMainThread()) {
+        PAUSEPOINT("search_term_predicate");
+      }
```
Comment (KarthikSubbarao) [inline src/indexes/text.cc]: This is not on the main thread

Comment (KarthikSubbarao) [reply src/indexes/text.cc]: Also, what was the purpose of adding the pause point here and not on the other predicates? I am trying to understand what you are planning on testing with this

File: src/query/predicate.cc [hunk 6]
```diff
@@ -165,6 +169,9 @@ EvaluationResult PrefixPredicate::Evaluate(
   uint32_t max_words = options::GetMaxTermExpansions().GetValue();
   uint32_t word_count = 0;
   while (!word_iter.Done() && word_count < max_words) {
+    if (!vmsdk::IsMainThread()) {
```
Comment (KarthikSubbarao) [inline src/query/predicate.cc]: It would be nice to have a helper function which helps us avoid having to add this check everywhere:
```
if (!vmsdk::IsMainThread()) 
```

File: integration/test_cancel.py (hunk 4 above)
Comment (Arunsarma07) [reply integration/test_cancel.py:12]: I have added a dedicated test to hit the each of the pausepoints to see if the command times out. I'll see if I can reuse some existing methods but I think it is mostly the new tests.

File: src/indexes/text.cc (hunk 5 above)
Comment (Arunsarma07) [reply src/indexes/text.cc]: I have added the same pausepoint in the `predicate.cc` file in the `Evaluate` method for other predicates too. I thought I cleaned it up while fixing the integration tests but missed it. I will remove this.

File: vmsdk/src/debug.h [hunk 7]
```diff
@@ -34,6 +34,12 @@ namespace debug {
   vmsdk::debug::PausePoint(name, std::source_location::current())
 void PausePoint(absl::string_view point, std::source_location location);
 
+#define BACKGROUND_PAUSEPOINT(name) \
+  do {                              \
```
Comment (KarthikSubbarao) [inline vmsdk/src/debug.h]: Can we remove the while loop?

File: integration/test_cancel.py [hunk 8]
```diff
@@ -62,6 +64,110 @@ def search(
             assert str(e) == "Search operation cancelled due to timeout"
         return []
 
+def wait_for_pausepoint(client: Valkey, pausepoint_name: str, timeout: int = 5) -> bool:
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Can we move this to utilities?

File: integration/test_cancel.py [hunk 9]
```diff
@@ -62,6 +64,110 @@ def search(
...
+    """
+    Wait for a pausepoint to be hit by at least one thread.
+    """
+    start = time.time()
+    while time.time() - start < timeout:
+        count = client.execute_command("FT._DEBUG", "PAUSEPOINT", "TEST", pausepoint_name)
+        if count > 0:
+            return True
+        time.sleep(0.1)
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: It is not ideal to use time.sleep in tests since it can be flaky based on where it is used

File: integration/test_cancel.py [hunk 10]
```diff
@@ -62,6 +64,110 @@ def search(
...
+        return result
+    except ResponseError as e:
+        if not expect_timeout:
+            raise
+        error_msg = str(e)
+        assert "cancelled due to timeout" in error_msg, f"Expected timeout error, got: {error_msg}"
+        return []
+
+
+def run_pausepoint_timeout_test(self, pausepoint_name, setup_fn, search_cmd, timeout_ms=5000):
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Is this a utility function as well?

File: integration/test_cancel.py [hunk 11]
```diff
@@ -62,6 +64,110 @@ def search(
...
+    3. Timeout fires and command returns error
+
+    Args:
+        pausepoint_name: Name of the pausepoint to set
+        setup_fn: Callable(client) that creates indexes and loads data
+        search_cmd: List of command args to execute as the search.
+        timeout_ms: Timeout in milliseconds for the search command
+    """
+    client = self.server.get_new_client()
+    client.execute_command("FLUSHALL", "SYNC")
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Why do we need to flush here?

File: integration/test_cancel.py [hunk 12]
```diff
@@ -62,6 +64,110 @@ def search(
...
+
+    thread = threading.Thread(target=run_search)
+    thread.start()
+
+    assert wait_for_pausepoint(client, pausepoint_name, timeout=10), \
+        f"Pausepoint {pausepoint_name} was not hit"
+    assert client.ping() == True, "Server not responsive while pausepoint is held"
+
+    # Wait for timeout to fire (timeout_ms + 1s buffer)
+    time.sleep(timeout_ms / 1000 + 1)
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Is this needed?

File: integration/test_cancel.py (hunk 8 above)
Comment (Arunsarma07) [reply integration/test_cancel.py]: Will move it to utilities.

File: vmsdk/src/debug.h (hunk 7 above)
Comment (Arunsarma07) [reply vmsdk/src/debug.h]: Will remove this.

File: integration/test_cancel.py (hunk 9 above)
Comment (Arunsarma07) [reply integration/test_cancel.py]: I can change this to `waiters.wait_for_true`.

File: integration/test_cancel.py (hunk 11 above)
Comment (Arunsarma07) [reply integration/test_cancel.py]: It helps in isolating each test so leftover state from a prior test doesn't interfere.

File: integration/test_cancel.py (hunk 12 above)
Comment (Arunsarma07) [reply integration/test_cancel.py]: The search command has timeout of 5 sec and I'm waiting till the timeout is occurred and the thread is stuck at the pausepoint. Without the sleep I will be resetting the pausepoint before it hits.

File: integration/test_cancel.py (hunk 11 above)
Comment (KarthikSubbarao) [reply integration/test_cancel.py]: Each test here is running on a new server, so it is not needed. if you combine the search tests into a single test fn, it is needed

File: integration/test_cancel.py (hunk 12 above)
Comment (KarthikSubbarao) [reply integration/test_cancel.py]: We want to test whether we are able to break out of inf loops (if any exist today due to bugs). We should be able to safely timeout from these operations without causing the module to be stuck / thread to be stuck running

File: integration/test_cancel.py [hunk 13]
```diff
@@ -62,6 +64,110 @@ def search(
...
+
+    client.execute_command("FT._DEBUG", "PAUSEPOINT", "RESET", pausepoint_name)
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Let's remove this

File: integration/test_cancel.py (hunk 12 above)
Comment (KarthikSubbarao) [reply integration/test_cancel.py]: We can wait until the blocked client count increments instead of a time.sleep

File: integration/test_cancel.py [hunk 14]
```diff
@@ -62,6 +64,110 @@ def search(
...
+    try:
+        result = client.execute_command(*cmd)
+        if expect_timeout:
+            assert False, f"Expected timeout but got result: {result}"
+        return result
+    except ResponseError as e:
+        if not expect_timeout:
+            raise
+        error_msg = str(e)
+        assert "cancelled due to timeout" in error_msg, f"Expected timeout error, got: {error_msg}"
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: Let's add the full message here. Check that it is timing out from the aggregate path

File: integration/test_cancel.py [hunk 15]
```diff
@@ -180,6 +286,192 @@ def test_timeoutCMD(self):
...
+        # Baseline - verify normal operation
+        nominal_hnsw = aggregate(client, "hnsw", False, stages=["LOAD", "1", "@n"])
+        nominal_flat = aggregate(client, "flat", False, stages=["LOAD", "1", "@n"])
+        assert nominal_hnsw[0] == 10
+        assert nominal_flat[0] == 10
+        assert client.info("SEARCH")["search_cancel-timeouts"] == 0
+        
+        # Enable forced timeouts
+        assert client.execute_command("FT._DEBUG CONTROLLED_VARIABLE SET ForceTimeout yes") == b"OK"
+        assert client.execute_command("ft._debug CONTROLLED_VARIABLE SET timeoutpollfrequency 1") == b"OK"
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py]: This is not testing the Aggregate Stage based timeout. It is going to force a timeout in the background search and later force the error message in the SendReply before entering the aggregate stage logic

File: integration/test_cancel.py (hunk 10 above)
Comment (KarthikSubbarao) [reply integration/test_cancel.py]: lets remove timeout_ms

File: integration/test_cancel.py [hunk 16]
```diff
@@ -287,3 +562,37 @@ def test_timeoutCME(self):
         self.check_info_sum("search_query_prefiltering_requests_cnt", 6)
         self.check_info_sum("search_test-counter-ForceCancels", 9)
 
+    def test_aggregate_timeout_cluster(self):
+        """Test FT.AGGREGATE timeout handling in cluster mode."""
+        self.execute_primaries(["flushall sync"])
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py:567]: Not needed. This is on a new test and new server

File: integration/test_cancel.py [hunk 17]
```diff
@@ -180,6 +270,191 @@ def test_timeoutCMD(self):
...
+
+        run_pausepoint_timeout_test(
+            self, "search_composed_predicate", setup,
+            ["FT.SEARCH", "idx", "(@text:word* | @tag:{tag1}) @num:[0 500]", "TIMEOUT", "5000"]
+        )
+
+    def test_aggregate_timeout(self):
+        """Test FT.AGGREGATE timeout handling across all aggregation stages."""
+        client: Valkey = self.server.get_new_client()
+        client.execute_command("FLUSHALL SYNC")
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py:408]: Not needed. This is on a new test and new server

File: integration/test_cancel.py [hunk 18]
```diff
@@ -287,3 +562,37 @@ def test_timeoutCME(self):
         self.check_info_sum("search_query_prefiltering_requests_cnt", 6)
         self.check_info_sum("search_test-counter-ForceCancels", 9)
 
+    def test_aggregate_timeout_cluster(self):
+        """Test FT.AGGREGATE timeout handling in cluster mode."""
+        self.execute_primaries(["flushall sync"])
+        self.config_set("search.info-developer-visible", "yes")
+
+        client: Valkey = self.new_cluster_client()
+        self.check_info("search_cancel-timeouts", 0)
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py:571]: What is this check helping with?

File: integration/test_cancel.py [hunk 19]
```diff
@@ -180,6 +270,191 @@ def test_timeoutCMD(self):
...
+        hnsw_index.create(client)
+        flat_index.create(client)
+        hnsw_index.load_data(client, 1000)
+        
+        # Baseline - verify normal operation
+        nominal_hnsw = aggregate(client, "hnsw", False, stages=["LOAD", "1", "@n"])
+        nominal_flat = aggregate(client, "flat", False, stages=["LOAD", "1", "@n"])
+        assert nominal_hnsw[0] == 10
+        assert nominal_flat[0] == 10
+        assert client.info("SEARCH")["search_cancel-timeouts"] == 0
```
Comment (KarthikSubbarao) [inline integration/test_cancel.py:425]: What is this check helping with?
